import { readFileSync, writeFileSync } from 'node:fs';
import { formatHex, formatHex8, parse } from 'culori';
const css = readFileSync('node_modules/tailwindcss/theme.css', 'utf8');
const version = JSON.parse(readFileSync('node_modules/tailwindcss/package.json', 'utf8')).version;
const declarations = text => [...text.matchAll(/--([\w-]+):\s*([^;]+);/g)].map(([,name,value]) => [name,value.trim()]);
const presets = [];
function add(source, name, kind, day, night = day) { presets.push({ id: `${source}/${name}`, name, kind, day, night }); }
function color(value) {
 const parsed = parse(value);
 if (!parsed) throw Error(`Cannot convert ${value}`);
 return parsed.alpha !== undefined && parsed.alpha < 1 ? formatHex8(parsed) : formatHex(parsed);
}
for (const [name,value] of declarations(css)) {
 if (name.startsWith('color-')) continue; // Colors default to shadcn Neutral only.
 else if (/^text-[^-]+$/.test(name) && /^[-\d.]+rem$/.test(value)) add('shadcn', name, 'fontSize', parseFloat(value) * 16);
 else if (/^shadow-(2xs|xs|sm|md|lg|xl|2xl)$/.test(name)) add('shadcn',name,'shadow',value.replace(/rgb\([^)]*\)/g, match => color(match)));
 else if (name.startsWith('font-weight-')) add('shadcn', 'font-' + name.slice(12), 'fontWeight', Number(value));
 else if (name.startsWith('tracking-')) add('shadcn', name, 'letterSpacing', parseFloat(value) * 16);

}
add('shadcn','shadow-none','shadow','none');

const shadcn = readFileSync('presets/shadcn-neutral.css', 'utf8');
const light = new Map(declarations(shadcn.match(/:root\s*\{([\s\S]*?)\}/)[1]));
const dark = new Map(declarations(shadcn.match(/\.dark\s*\{([\s\S]*?)\}/)[1]));
// Monochromatic adaptation requested by the user: keep lightness/alpha, remove chart/error chroma.
const monochrome = value => value.replace(/(oklch\([^\s]+)\s+[^\s]+/, '$1 0');
for (const [name,value] of light) if(name !== 'radius') add('shadcn',name,'colors',color(monochrome(value)),color(monochrome(dark.get(name) || value)));
const radius = parseFloat(light.get('radius')) * 16;
add('shadcn','radius','borderRadius',radius);
for (const [size,multiplier] of [['sm',.6],['md',.8],['lg',1],['xl',1.4],['2xl',1.8],['3xl',2.2],['4xl',2.6]]) add('shadcn','radius-'+size,'borderRadius',radius*multiplier);
writeFileSync('src/presets.ts', `// Generated by scripts/generate-presets.mjs. Tailwind ${version}; shadcn neutral snapshot.\nexport type PresetKind = "colors" | "fontSize" | "fontWeight" | "letterSpacing" | "borderRadius" | "shadow";\nexport type Preset = { id: string; name: string; kind: PresetKind; day: string | number; night: string | number };\nexport const presets: Preset[] = ${JSON.stringify(presets,null,2)};\n`);
console.log(`${presets.length} presets generated from Tailwind ${version} and shadcn neutral.`);
