// Generated by scripts/generate-presets.mjs. Tailwind 4.3.3; shadcn neutral snapshot.
export type PresetKind = "colors" | "fontSize" | "fontWeight" | "letterSpacing" | "borderRadius" | "shadow" | "height" | "width";
export type Preset = { id: string; name: string; kind: PresetKind; day: string | number; night: string | number };
export const presets: Preset[] = [
  {
    "id": "shadcn/text-xs",
    "name": "text-xs",
    "kind": "fontSize",
    "day": 12,
    "night": 12
  },
  {
    "id": "shadcn/text-sm",
    "name": "text-sm",
    "kind": "fontSize",
    "day": 14,
    "night": 14
  },
  {
    "id": "shadcn/text-base",
    "name": "text-base",
    "kind": "fontSize",
    "day": 16,
    "night": 16
  },
  {
    "id": "shadcn/text-lg",
    "name": "text-lg",
    "kind": "fontSize",
    "day": 18,
    "night": 18
  },
  {
    "id": "shadcn/text-xl",
    "name": "text-xl",
    "kind": "fontSize",
    "day": 20,
    "night": 20
  },
  {
    "id": "shadcn/text-2xl",
    "name": "text-2xl",
    "kind": "fontSize",
    "day": 24,
    "night": 24
  },
  {
    "id": "shadcn/text-3xl",
    "name": "text-3xl",
    "kind": "fontSize",
    "day": 30,
    "night": 30
  },
  {
    "id": "shadcn/text-4xl",
    "name": "text-4xl",
    "kind": "fontSize",
    "day": 36,
    "night": 36
  },
  {
    "id": "shadcn/text-5xl",
    "name": "text-5xl",
    "kind": "fontSize",
    "day": 48,
    "night": 48
  },
  {
    "id": "shadcn/text-6xl",
    "name": "text-6xl",
    "kind": "fontSize",
    "day": 60,
    "night": 60
  },
  {
    "id": "shadcn/text-7xl",
    "name": "text-7xl",
    "kind": "fontSize",
    "day": 72,
    "night": 72
  },
  {
    "id": "shadcn/text-8xl",
    "name": "text-8xl",
    "kind": "fontSize",
    "day": 96,
    "night": 96
  },
  {
    "id": "shadcn/text-9xl",
    "name": "text-9xl",
    "kind": "fontSize",
    "day": 128,
    "night": 128
  },
  {
    "id": "shadcn/font-thin",
    "name": "font-thin",
    "kind": "fontWeight",
    "day": 100,
    "night": 100
  },
  {
    "id": "shadcn/font-extralight",
    "name": "font-extralight",
    "kind": "fontWeight",
    "day": 200,
    "night": 200
  },
  {
    "id": "shadcn/font-light",
    "name": "font-light",
    "kind": "fontWeight",
    "day": 300,
    "night": 300
  },
  {
    "id": "shadcn/font-normal",
    "name": "font-normal",
    "kind": "fontWeight",
    "day": 400,
    "night": 400
  },
  {
    "id": "shadcn/font-medium",
    "name": "font-medium",
    "kind": "fontWeight",
    "day": 500,
    "night": 500
  },
  {
    "id": "shadcn/font-semibold",
    "name": "font-semibold",
    "kind": "fontWeight",
    "day": 600,
    "night": 600
  },
  {
    "id": "shadcn/font-bold",
    "name": "font-bold",
    "kind": "fontWeight",
    "day": 700,
    "night": 700
  },
  {
    "id": "shadcn/font-extrabold",
    "name": "font-extrabold",
    "kind": "fontWeight",
    "day": 800,
    "night": 800
  },
  {
    "id": "shadcn/font-black",
    "name": "font-black",
    "kind": "fontWeight",
    "day": 900,
    "night": 900
  },
  {
    "id": "shadcn/tracking-tighter",
    "name": "tracking-tighter",
    "kind": "letterSpacing",
    "day": -0.8,
    "night": -0.8
  },
  {
    "id": "shadcn/tracking-tight",
    "name": "tracking-tight",
    "kind": "letterSpacing",
    "day": -0.4,
    "night": -0.4
  },
  {
    "id": "shadcn/tracking-normal",
    "name": "tracking-normal",
    "kind": "letterSpacing",
    "day": 0,
    "night": 0
  },
  {
    "id": "shadcn/tracking-wide",
    "name": "tracking-wide",
    "kind": "letterSpacing",
    "day": 0.4,
    "night": 0.4
  },
  {
    "id": "shadcn/tracking-wider",
    "name": "tracking-wider",
    "kind": "letterSpacing",
    "day": 0.8,
    "night": 0.8
  },
  {
    "id": "shadcn/tracking-widest",
    "name": "tracking-widest",
    "kind": "letterSpacing",
    "day": 1.6,
    "night": 1.6
  },
  {
    "id": "shadcn/shadow-2xs",
    "name": "shadow-2xs",
    "kind": "shadow",
    "day": "0 1px #0000000d",
    "night": "0 1px #0000000d"
  },
  {
    "id": "shadcn/shadow-xs",
    "name": "shadow-xs",
    "kind": "shadow",
    "day": "0 1px 2px 0 #0000000d",
    "night": "0 1px 2px 0 #0000000d"
  },
  {
    "id": "shadcn/shadow-sm",
    "name": "shadow-sm",
    "kind": "shadow",
    "day": "0 1px 3px 0 #0000001a, 0 1px 2px -1px #0000001a",
    "night": "0 1px 3px 0 #0000001a, 0 1px 2px -1px #0000001a"
  },
  {
    "id": "shadcn/shadow-md",
    "name": "shadow-md",
    "kind": "shadow",
    "day": "0 4px 6px -1px #0000001a, 0 2px 4px -2px #0000001a",
    "night": "0 4px 6px -1px #0000001a, 0 2px 4px -2px #0000001a"
  },
  {
    "id": "shadcn/shadow-lg",
    "name": "shadow-lg",
    "kind": "shadow",
    "day": "0 10px 15px -3px #0000001a, 0 4px 6px -4px #0000001a",
    "night": "0 10px 15px -3px #0000001a, 0 4px 6px -4px #0000001a"
  },
  {
    "id": "shadcn/shadow-xl",
    "name": "shadow-xl",
    "kind": "shadow",
    "day": "0 20px 25px -5px #0000001a, 0 8px 10px -6px #0000001a",
    "night": "0 20px 25px -5px #0000001a, 0 8px 10px -6px #0000001a"
  },
  {
    "id": "shadcn/shadow-2xl",
    "name": "shadow-2xl",
    "kind": "shadow",
    "day": "0 25px 50px -12px #00000040",
    "night": "0 25px 50px -12px #00000040"
  },
  {
    "id": "shadcn/shadow-none",
    "name": "shadow-none",
    "kind": "shadow",
    "day": "none",
    "night": "none"
  },
  {
    "id": "shadcn/h-px",
    "name": "h-px",
    "kind": "height",
    "day": 1,
    "night": 1
  },
  {
    "id": "shadcn/h-0",
    "name": "h-0",
    "kind": "height",
    "day": 0,
    "night": 0
  },
  {
    "id": "shadcn/h-0.5",
    "name": "h-0_5",
    "kind": "height",
    "day": 2,
    "night": 2
  },
  {
    "id": "shadcn/h-1",
    "name": "h-1",
    "kind": "height",
    "day": 4,
    "night": 4
  },
  {
    "id": "shadcn/h-1.5",
    "name": "h-1_5",
    "kind": "height",
    "day": 6,
    "night": 6
  },
  {
    "id": "shadcn/h-2",
    "name": "h-2",
    "kind": "height",
    "day": 8,
    "night": 8
  },
  {
    "id": "shadcn/h-2.5",
    "name": "h-2_5",
    "kind": "height",
    "day": 10,
    "night": 10
  },
  {
    "id": "shadcn/h-3",
    "name": "h-3",
    "kind": "height",
    "day": 12,
    "night": 12
  },
  {
    "id": "shadcn/h-3.5",
    "name": "h-3_5",
    "kind": "height",
    "day": 14,
    "night": 14
  },
  {
    "id": "shadcn/h-4",
    "name": "h-4",
    "kind": "height",
    "day": 16,
    "night": 16
  },
  {
    "id": "shadcn/h-5",
    "name": "h-5",
    "kind": "height",
    "day": 20,
    "night": 20
  },
  {
    "id": "shadcn/h-6",
    "name": "h-6",
    "kind": "height",
    "day": 24,
    "night": 24
  },
  {
    "id": "shadcn/h-7",
    "name": "h-7",
    "kind": "height",
    "day": 28,
    "night": 28
  },
  {
    "id": "shadcn/h-8",
    "name": "h-8",
    "kind": "height",
    "day": 32,
    "night": 32
  },
  {
    "id": "shadcn/h-9",
    "name": "h-9",
    "kind": "height",
    "day": 36,
    "night": 36
  },
  {
    "id": "shadcn/h-10",
    "name": "h-10",
    "kind": "height",
    "day": 40,
    "night": 40
  },
  {
    "id": "shadcn/h-11",
    "name": "h-11",
    "kind": "height",
    "day": 44,
    "night": 44
  },
  {
    "id": "shadcn/h-12",
    "name": "h-12",
    "kind": "height",
    "day": 48,
    "night": 48
  },
  {
    "id": "shadcn/h-14",
    "name": "h-14",
    "kind": "height",
    "day": 56,
    "night": 56
  },
  {
    "id": "shadcn/h-16",
    "name": "h-16",
    "kind": "height",
    "day": 64,
    "night": 64
  },
  {
    "id": "shadcn/h-20",
    "name": "h-20",
    "kind": "height",
    "day": 80,
    "night": 80
  },
  {
    "id": "shadcn/h-24",
    "name": "h-24",
    "kind": "height",
    "day": 96,
    "night": 96
  },
  {
    "id": "shadcn/h-28",
    "name": "h-28",
    "kind": "height",
    "day": 112,
    "night": 112
  },
  {
    "id": "shadcn/h-32",
    "name": "h-32",
    "kind": "height",
    "day": 128,
    "night": 128
  },
  {
    "id": "shadcn/h-36",
    "name": "h-36",
    "kind": "height",
    "day": 144,
    "night": 144
  },
  {
    "id": "shadcn/h-40",
    "name": "h-40",
    "kind": "height",
    "day": 160,
    "night": 160
  },
  {
    "id": "shadcn/h-44",
    "name": "h-44",
    "kind": "height",
    "day": 176,
    "night": 176
  },
  {
    "id": "shadcn/h-48",
    "name": "h-48",
    "kind": "height",
    "day": 192,
    "night": 192
  },
  {
    "id": "shadcn/h-52",
    "name": "h-52",
    "kind": "height",
    "day": 208,
    "night": 208
  },
  {
    "id": "shadcn/h-56",
    "name": "h-56",
    "kind": "height",
    "day": 224,
    "night": 224
  },
  {
    "id": "shadcn/h-60",
    "name": "h-60",
    "kind": "height",
    "day": 240,
    "night": 240
  },
  {
    "id": "shadcn/h-64",
    "name": "h-64",
    "kind": "height",
    "day": 256,
    "night": 256
  },
  {
    "id": "shadcn/h-72",
    "name": "h-72",
    "kind": "height",
    "day": 288,
    "night": 288
  },
  {
    "id": "shadcn/h-80",
    "name": "h-80",
    "kind": "height",
    "day": 320,
    "night": 320
  },
  {
    "id": "shadcn/h-96",
    "name": "h-96",
    "kind": "height",
    "day": 384,
    "night": 384
  },
  {
    "id": "shadcn/w-px",
    "name": "w-px",
    "kind": "width",
    "day": 1,
    "night": 1
  },
  {
    "id": "shadcn/w-0",
    "name": "w-0",
    "kind": "width",
    "day": 0,
    "night": 0
  },
  {
    "id": "shadcn/w-0.5",
    "name": "w-0_5",
    "kind": "width",
    "day": 2,
    "night": 2
  },
  {
    "id": "shadcn/w-1",
    "name": "w-1",
    "kind": "width",
    "day": 4,
    "night": 4
  },
  {
    "id": "shadcn/w-1.5",
    "name": "w-1_5",
    "kind": "width",
    "day": 6,
    "night": 6
  },
  {
    "id": "shadcn/w-2",
    "name": "w-2",
    "kind": "width",
    "day": 8,
    "night": 8
  },
  {
    "id": "shadcn/w-2.5",
    "name": "w-2_5",
    "kind": "width",
    "day": 10,
    "night": 10
  },
  {
    "id": "shadcn/w-3",
    "name": "w-3",
    "kind": "width",
    "day": 12,
    "night": 12
  },
  {
    "id": "shadcn/w-3.5",
    "name": "w-3_5",
    "kind": "width",
    "day": 14,
    "night": 14
  },
  {
    "id": "shadcn/w-4",
    "name": "w-4",
    "kind": "width",
    "day": 16,
    "night": 16
  },
  {
    "id": "shadcn/w-5",
    "name": "w-5",
    "kind": "width",
    "day": 20,
    "night": 20
  },
  {
    "id": "shadcn/w-6",
    "name": "w-6",
    "kind": "width",
    "day": 24,
    "night": 24
  },
  {
    "id": "shadcn/w-7",
    "name": "w-7",
    "kind": "width",
    "day": 28,
    "night": 28
  },
  {
    "id": "shadcn/w-8",
    "name": "w-8",
    "kind": "width",
    "day": 32,
    "night": 32
  },
  {
    "id": "shadcn/w-9",
    "name": "w-9",
    "kind": "width",
    "day": 36,
    "night": 36
  },
  {
    "id": "shadcn/w-10",
    "name": "w-10",
    "kind": "width",
    "day": 40,
    "night": 40
  },
  {
    "id": "shadcn/w-11",
    "name": "w-11",
    "kind": "width",
    "day": 44,
    "night": 44
  },
  {
    "id": "shadcn/w-12",
    "name": "w-12",
    "kind": "width",
    "day": 48,
    "night": 48
  },
  {
    "id": "shadcn/w-14",
    "name": "w-14",
    "kind": "width",
    "day": 56,
    "night": 56
  },
  {
    "id": "shadcn/w-16",
    "name": "w-16",
    "kind": "width",
    "day": 64,
    "night": 64
  },
  {
    "id": "shadcn/w-20",
    "name": "w-20",
    "kind": "width",
    "day": 80,
    "night": 80
  },
  {
    "id": "shadcn/w-24",
    "name": "w-24",
    "kind": "width",
    "day": 96,
    "night": 96
  },
  {
    "id": "shadcn/w-28",
    "name": "w-28",
    "kind": "width",
    "day": 112,
    "night": 112
  },
  {
    "id": "shadcn/w-32",
    "name": "w-32",
    "kind": "width",
    "day": 128,
    "night": 128
  },
  {
    "id": "shadcn/w-36",
    "name": "w-36",
    "kind": "width",
    "day": 144,
    "night": 144
  },
  {
    "id": "shadcn/w-40",
    "name": "w-40",
    "kind": "width",
    "day": 160,
    "night": 160
  },
  {
    "id": "shadcn/w-44",
    "name": "w-44",
    "kind": "width",
    "day": 176,
    "night": 176
  },
  {
    "id": "shadcn/w-48",
    "name": "w-48",
    "kind": "width",
    "day": 192,
    "night": 192
  },
  {
    "id": "shadcn/w-52",
    "name": "w-52",
    "kind": "width",
    "day": 208,
    "night": 208
  },
  {
    "id": "shadcn/w-56",
    "name": "w-56",
    "kind": "width",
    "day": 224,
    "night": 224
  },
  {
    "id": "shadcn/w-60",
    "name": "w-60",
    "kind": "width",
    "day": 240,
    "night": 240
  },
  {
    "id": "shadcn/w-64",
    "name": "w-64",
    "kind": "width",
    "day": 256,
    "night": 256
  },
  {
    "id": "shadcn/w-72",
    "name": "w-72",
    "kind": "width",
    "day": 288,
    "night": 288
  },
  {
    "id": "shadcn/w-80",
    "name": "w-80",
    "kind": "width",
    "day": 320,
    "night": 320
  },
  {
    "id": "shadcn/w-96",
    "name": "w-96",
    "kind": "width",
    "day": 384,
    "night": 384
  },
  {
    "id": "shadcn/background",
    "name": "background",
    "kind": "colors",
    "day": "#ffffff",
    "night": "#0a0a0a"
  },
  {
    "id": "shadcn/foreground",
    "name": "foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/card",
    "name": "card",
    "kind": "colors",
    "day": "#ffffff",
    "night": "#171717"
  },
  {
    "id": "shadcn/card-foreground",
    "name": "card-foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/popover",
    "name": "popover",
    "kind": "colors",
    "day": "#ffffff",
    "night": "#171717"
  },
  {
    "id": "shadcn/popover-foreground",
    "name": "popover-foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/primary",
    "name": "primary",
    "kind": "colors",
    "day": "#171717",
    "night": "#e5e5e5"
  },
  {
    "id": "shadcn/primary-foreground",
    "name": "primary-foreground",
    "kind": "colors",
    "day": "#fafafa",
    "night": "#171717"
  },
  {
    "id": "shadcn/secondary",
    "name": "secondary",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/secondary-foreground",
    "name": "secondary-foreground",
    "kind": "colors",
    "day": "#171717",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/muted",
    "name": "muted",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/muted-foreground",
    "name": "muted-foreground",
    "kind": "colors",
    "day": "#737373",
    "night": "#a1a1a1"
  },
  {
    "id": "shadcn/accent",
    "name": "accent",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/accent-foreground",
    "name": "accent-foreground",
    "kind": "colors",
    "day": "#171717",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/destructive",
    "name": "destructive",
    "kind": "colors",
    "day": "#797979",
    "night": "#9f9f9f"
  },
  {
    "id": "shadcn/border",
    "name": "border",
    "kind": "colors",
    "day": "#e5e5e5",
    "night": "#ffffff1a"
  },
  {
    "id": "shadcn/input",
    "name": "input",
    "kind": "colors",
    "day": "#e5e5e5",
    "night": "#ffffff26"
  },
  {
    "id": "shadcn/ring",
    "name": "ring",
    "kind": "colors",
    "day": "#a1a1a1",
    "night": "#737373"
  },
  {
    "id": "shadcn/chart-1",
    "name": "chart-1",
    "kind": "colors",
    "day": "#8e8e8e",
    "night": "#606060"
  },
  {
    "id": "shadcn/chart-2",
    "name": "chart-2",
    "kind": "colors",
    "day": "#808080",
    "night": "#9d9d9d"
  },
  {
    "id": "shadcn/chart-3",
    "name": "chart-3",
    "kind": "colors",
    "day": "#474747",
    "night": "#b4b4b4"
  },
  {
    "id": "shadcn/chart-4",
    "name": "chart-4",
    "kind": "colors",
    "day": "#c6c6c6",
    "night": "#888888"
  },
  {
    "id": "shadcn/chart-5",
    "name": "chart-5",
    "kind": "colors",
    "day": "#b4b4b4",
    "night": "#8d8d8d"
  },
  {
    "id": "shadcn/sidebar",
    "name": "sidebar",
    "kind": "colors",
    "day": "#fafafa",
    "night": "#171717"
  },
  {
    "id": "shadcn/sidebar-foreground",
    "name": "sidebar-foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/sidebar-primary",
    "name": "sidebar-primary",
    "kind": "colors",
    "day": "#171717",
    "night": "#606060"
  },
  {
    "id": "shadcn/sidebar-primary-foreground",
    "name": "sidebar-primary-foreground",
    "kind": "colors",
    "day": "#fafafa",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/sidebar-accent",
    "name": "sidebar-accent",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/sidebar-accent-foreground",
    "name": "sidebar-accent-foreground",
    "kind": "colors",
    "day": "#171717",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/sidebar-border",
    "name": "sidebar-border",
    "kind": "colors",
    "day": "#e5e5e5",
    "night": "#ffffff1a"
  },
  {
    "id": "shadcn/sidebar-ring",
    "name": "sidebar-ring",
    "kind": "colors",
    "day": "#a1a1a1",
    "night": "#737373"
  },
  {
    "id": "shadcn/radius",
    "name": "radius",
    "kind": "borderRadius",
    "day": 10,
    "night": 10
  },
  {
    "id": "shadcn/radius-sm",
    "name": "radius-sm",
    "kind": "borderRadius",
    "day": 6,
    "night": 6
  },
  {
    "id": "shadcn/radius-md",
    "name": "radius-md",
    "kind": "borderRadius",
    "day": 8,
    "night": 8
  },
  {
    "id": "shadcn/radius-lg",
    "name": "radius-lg",
    "kind": "borderRadius",
    "day": 10,
    "night": 10
  },
  {
    "id": "shadcn/radius-xl",
    "name": "radius-xl",
    "kind": "borderRadius",
    "day": 14,
    "night": 14
  },
  {
    "id": "shadcn/radius-2xl",
    "name": "radius-2xl",
    "kind": "borderRadius",
    "day": 18,
    "night": 18
  },
  {
    "id": "shadcn/radius-3xl",
    "name": "radius-3xl",
    "kind": "borderRadius",
    "day": 22,
    "night": 22
  },
  {
    "id": "shadcn/radius-4xl",
    "name": "radius-4xl",
    "kind": "borderRadius",
    "day": 26,
    "night": 26
  }
];
