// Generated by scripts/generate-presets.mjs. Tailwind 4.3.3; shadcn neutral snapshot.
export type PresetKind = "colors" | "fontSize" | "fontWeight" | "letterSpacing" | "borderRadius" | "shadow";
export type Preset = { id: string; name: string; kind: PresetKind; day: string | number; night: string | number };
export const presets: Preset[] = [
  {
    "id": "shadcn/text-xs",
    "name": "text-xs",
    "kind": "fontSize",
    "day": 12,
    "night": 12
  },
  {
    "id": "shadcn/text-sm",
    "name": "text-sm",
    "kind": "fontSize",
    "day": 14,
    "night": 14
  },
  {
    "id": "shadcn/text-base",
    "name": "text-base",
    "kind": "fontSize",
    "day": 16,
    "night": 16
  },
  {
    "id": "shadcn/text-lg",
    "name": "text-lg",
    "kind": "fontSize",
    "day": 18,
    "night": 18
  },
  {
    "id": "shadcn/text-xl",
    "name": "text-xl",
    "kind": "fontSize",
    "day": 20,
    "night": 20
  },
  {
    "id": "shadcn/text-2xl",
    "name": "text-2xl",
    "kind": "fontSize",
    "day": 24,
    "night": 24
  },
  {
    "id": "shadcn/text-3xl",
    "name": "text-3xl",
    "kind": "fontSize",
    "day": 30,
    "night": 30
  },
  {
    "id": "shadcn/text-4xl",
    "name": "text-4xl",
    "kind": "fontSize",
    "day": 36,
    "night": 36
  },
  {
    "id": "shadcn/text-5xl",
    "name": "text-5xl",
    "kind": "fontSize",
    "day": 48,
    "night": 48
  },
  {
    "id": "shadcn/text-6xl",
    "name": "text-6xl",
    "kind": "fontSize",
    "day": 60,
    "night": 60
  },
  {
    "id": "shadcn/text-7xl",
    "name": "text-7xl",
    "kind": "fontSize",
    "day": 72,
    "night": 72
  },
  {
    "id": "shadcn/text-8xl",
    "name": "text-8xl",
    "kind": "fontSize",
    "day": 96,
    "night": 96
  },
  {
    "id": "shadcn/text-9xl",
    "name": "text-9xl",
    "kind": "fontSize",
    "day": 128,
    "night": 128
  },
  {
    "id": "shadcn/font-thin",
    "name": "font-thin",
    "kind": "fontWeight",
    "day": 100,
    "night": 100
  },
  {
    "id": "shadcn/font-extralight",
    "name": "font-extralight",
    "kind": "fontWeight",
    "day": 200,
    "night": 200
  },
  {
    "id": "shadcn/font-light",
    "name": "font-light",
    "kind": "fontWeight",
    "day": 300,
    "night": 300
  },
  {
    "id": "shadcn/font-normal",
    "name": "font-normal",
    "kind": "fontWeight",
    "day": 400,
    "night": 400
  },
  {
    "id": "shadcn/font-medium",
    "name": "font-medium",
    "kind": "fontWeight",
    "day": 500,
    "night": 500
  },
  {
    "id": "shadcn/font-semibold",
    "name": "font-semibold",
    "kind": "fontWeight",
    "day": 600,
    "night": 600
  },
  {
    "id": "shadcn/font-bold",
    "name": "font-bold",
    "kind": "fontWeight",
    "day": 700,
    "night": 700
  },
  {
    "id": "shadcn/font-extrabold",
    "name": "font-extrabold",
    "kind": "fontWeight",
    "day": 800,
    "night": 800
  },
  {
    "id": "shadcn/font-black",
    "name": "font-black",
    "kind": "fontWeight",
    "day": 900,
    "night": 900
  },
  {
    "id": "shadcn/tracking-tighter",
    "name": "tracking-tighter",
    "kind": "letterSpacing",
    "day": -0.8,
    "night": -0.8
  },
  {
    "id": "shadcn/tracking-tight",
    "name": "tracking-tight",
    "kind": "letterSpacing",
    "day": -0.4,
    "night": -0.4
  },
  {
    "id": "shadcn/tracking-normal",
    "name": "tracking-normal",
    "kind": "letterSpacing",
    "day": 0,
    "night": 0
  },
  {
    "id": "shadcn/tracking-wide",
    "name": "tracking-wide",
    "kind": "letterSpacing",
    "day": 0.4,
    "night": 0.4
  },
  {
    "id": "shadcn/tracking-wider",
    "name": "tracking-wider",
    "kind": "letterSpacing",
    "day": 0.8,
    "night": 0.8
  },
  {
    "id": "shadcn/tracking-widest",
    "name": "tracking-widest",
    "kind": "letterSpacing",
    "day": 1.6,
    "night": 1.6
  },
  {
    "id": "shadcn/shadow-2xs",
    "name": "shadow-2xs",
    "kind": "shadow",
    "day": "0 1px #0000000d",
    "night": "0 1px #0000000d"
  },
  {
    "id": "shadcn/shadow-xs",
    "name": "shadow-xs",
    "kind": "shadow",
    "day": "0 1px 2px 0 #0000000d",
    "night": "0 1px 2px 0 #0000000d"
  },
  {
    "id": "shadcn/shadow-sm",
    "name": "shadow-sm",
    "kind": "shadow",
    "day": "0 1px 3px 0 #0000001a, 0 1px 2px -1px #0000001a",
    "night": "0 1px 3px 0 #0000001a, 0 1px 2px -1px #0000001a"
  },
  {
    "id": "shadcn/shadow-md",
    "name": "shadow-md",
    "kind": "shadow",
    "day": "0 4px 6px -1px #0000001a, 0 2px 4px -2px #0000001a",
    "night": "0 4px 6px -1px #0000001a, 0 2px 4px -2px #0000001a"
  },
  {
    "id": "shadcn/shadow-lg",
    "name": "shadow-lg",
    "kind": "shadow",
    "day": "0 10px 15px -3px #0000001a, 0 4px 6px -4px #0000001a",
    "night": "0 10px 15px -3px #0000001a, 0 4px 6px -4px #0000001a"
  },
  {
    "id": "shadcn/shadow-xl",
    "name": "shadow-xl",
    "kind": "shadow",
    "day": "0 20px 25px -5px #0000001a, 0 8px 10px -6px #0000001a",
    "night": "0 20px 25px -5px #0000001a, 0 8px 10px -6px #0000001a"
  },
  {
    "id": "shadcn/shadow-2xl",
    "name": "shadow-2xl",
    "kind": "shadow",
    "day": "0 25px 50px -12px #00000040",
    "night": "0 25px 50px -12px #00000040"
  },
  {
    "id": "shadcn/shadow-none",
    "name": "shadow-none",
    "kind": "shadow",
    "day": "none",
    "night": "none"
  },
  {
    "id": "shadcn/background",
    "name": "background",
    "kind": "colors",
    "day": "#ffffff",
    "night": "#0a0a0a"
  },
  {
    "id": "shadcn/foreground",
    "name": "foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/card",
    "name": "card",
    "kind": "colors",
    "day": "#ffffff",
    "night": "#171717"
  },
  {
    "id": "shadcn/card-foreground",
    "name": "card-foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/popover",
    "name": "popover",
    "kind": "colors",
    "day": "#ffffff",
    "night": "#171717"
  },
  {
    "id": "shadcn/popover-foreground",
    "name": "popover-foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/primary",
    "name": "primary",
    "kind": "colors",
    "day": "#171717",
    "night": "#e5e5e5"
  },
  {
    "id": "shadcn/primary-foreground",
    "name": "primary-foreground",
    "kind": "colors",
    "day": "#fafafa",
    "night": "#171717"
  },
  {
    "id": "shadcn/secondary",
    "name": "secondary",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/secondary-foreground",
    "name": "secondary-foreground",
    "kind": "colors",
    "day": "#171717",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/muted",
    "name": "muted",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/muted-foreground",
    "name": "muted-foreground",
    "kind": "colors",
    "day": "#737373",
    "night": "#a1a1a1"
  },
  {
    "id": "shadcn/accent",
    "name": "accent",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/accent-foreground",
    "name": "accent-foreground",
    "kind": "colors",
    "day": "#171717",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/destructive",
    "name": "destructive",
    "kind": "colors",
    "day": "#797979",
    "night": "#9f9f9f"
  },
  {
    "id": "shadcn/border",
    "name": "border",
    "kind": "colors",
    "day": "#e5e5e5",
    "night": "#ffffff1a"
  },
  {
    "id": "shadcn/input",
    "name": "input",
    "kind": "colors",
    "day": "#e5e5e5",
    "night": "#ffffff26"
  },
  {
    "id": "shadcn/ring",
    "name": "ring",
    "kind": "colors",
    "day": "#a1a1a1",
    "night": "#737373"
  },
  {
    "id": "shadcn/chart-1",
    "name": "chart-1",
    "kind": "colors",
    "day": "#8e8e8e",
    "night": "#606060"
  },
  {
    "id": "shadcn/chart-2",
    "name": "chart-2",
    "kind": "colors",
    "day": "#808080",
    "night": "#9d9d9d"
  },
  {
    "id": "shadcn/chart-3",
    "name": "chart-3",
    "kind": "colors",
    "day": "#474747",
    "night": "#b4b4b4"
  },
  {
    "id": "shadcn/chart-4",
    "name": "chart-4",
    "kind": "colors",
    "day": "#c6c6c6",
    "night": "#888888"
  },
  {
    "id": "shadcn/chart-5",
    "name": "chart-5",
    "kind": "colors",
    "day": "#b4b4b4",
    "night": "#8d8d8d"
  },
  {
    "id": "shadcn/sidebar",
    "name": "sidebar",
    "kind": "colors",
    "day": "#fafafa",
    "night": "#171717"
  },
  {
    "id": "shadcn/sidebar-foreground",
    "name": "sidebar-foreground",
    "kind": "colors",
    "day": "#0a0a0a",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/sidebar-primary",
    "name": "sidebar-primary",
    "kind": "colors",
    "day": "#171717",
    "night": "#606060"
  },
  {
    "id": "shadcn/sidebar-primary-foreground",
    "name": "sidebar-primary-foreground",
    "kind": "colors",
    "day": "#fafafa",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/sidebar-accent",
    "name": "sidebar-accent",
    "kind": "colors",
    "day": "#f5f5f5",
    "night": "#262626"
  },
  {
    "id": "shadcn/sidebar-accent-foreground",
    "name": "sidebar-accent-foreground",
    "kind": "colors",
    "day": "#171717",
    "night": "#fafafa"
  },
  {
    "id": "shadcn/sidebar-border",
    "name": "sidebar-border",
    "kind": "colors",
    "day": "#e5e5e5",
    "night": "#ffffff1a"
  },
  {
    "id": "shadcn/sidebar-ring",
    "name": "sidebar-ring",
    "kind": "colors",
    "day": "#a1a1a1",
    "night": "#737373"
  },
  {
    "id": "shadcn/radius",
    "name": "radius",
    "kind": "borderRadius",
    "day": 10,
    "night": 10
  },
  {
    "id": "shadcn/radius-sm",
    "name": "radius-sm",
    "kind": "borderRadius",
    "day": 6,
    "night": 6
  },
  {
    "id": "shadcn/radius-md",
    "name": "radius-md",
    "kind": "borderRadius",
    "day": 8,
    "night": 8
  },
  {
    "id": "shadcn/radius-lg",
    "name": "radius-lg",
    "kind": "borderRadius",
    "day": 10,
    "night": 10
  },
  {
    "id": "shadcn/radius-xl",
    "name": "radius-xl",
    "kind": "borderRadius",
    "day": 14,
    "night": 14
  },
  {
    "id": "shadcn/radius-2xl",
    "name": "radius-2xl",
    "kind": "borderRadius",
    "day": 18,
    "night": 18
  },
  {
    "id": "shadcn/radius-3xl",
    "name": "radius-3xl",
    "kind": "borderRadius",
    "day": 22,
    "night": 22
  },
  {
    "id": "shadcn/radius-4xl",
    "name": "radius-4xl",
    "kind": "borderRadius",
    "day": 26,
    "night": 26
  }
];
